// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGJozT6_IqdegTtkaRFBKfTCviPe3xvtU',
    appId: '1:61535472161:web:4796ae3245172fc9743160',
    messagingSenderId: '61535472161',
    projectId: 'drivemate-88803',
    authDomain: 'drivemate-88803.firebaseapp.com',
    storageBucket: 'drivemate-88803.firebasestorage.app',
    measurementId: 'G-HQ0YY3FD6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2yoHWxMJGDgPtcIC3Jx0DKSvLzUjYNRA',
    appId: '1:61535472161:android:fd2b20baf2f81158743160',
    messagingSenderId: '61535472161',
    projectId: 'drivemate-88803',
    storageBucket: 'drivemate-88803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIu_DD_wnFdGldgncKjW9JTyn4csBJ4Wg',
    appId: '1:61535472161:ios:67c966aeb576006d743160',
    messagingSenderId: '61535472161',
    projectId: 'drivemate-88803',
    storageBucket: 'drivemate-88803.firebasestorage.app',
    iosBundleId: 'com.example.test08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIu_DD_wnFdGldgncKjW9JTyn4csBJ4Wg',
    appId: '1:61535472161:ios:67c966aeb576006d743160',
    messagingSenderId: '61535472161',
    projectId: 'drivemate-88803',
    storageBucket: 'drivemate-88803.firebasestorage.app',
    iosBundleId: 'com.example.test08',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGJozT6_IqdegTtkaRFBKfTCviPe3xvtU',
    appId: '1:61535472161:web:eec38ddf3bb51953743160',
    messagingSenderId: '61535472161',
    projectId: 'drivemate-88803',
    authDomain: 'drivemate-88803.firebaseapp.com',
    storageBucket: 'drivemate-88803.firebasestorage.app',
    measurementId: 'G-407RCWX3YD',
  );
}
