name: Build and deploy NestJS app to Azure Web App - drivemate
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Only trigger on changes in backend folder
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install dependencies
        run: |
          npm ci
          npm install -g prisma
          npm install --save-dev @types/bcrypt @types/passport-jwt
      
      - name: Generate Prisma client
        run: npx prisma generate
      
      - name: Build application
        run: npm run build
        continue-on-error: false
      
      - name: Run tests (non-blocking)
        run: npm test || echo "Tests failed but continuing deployment"
        continue-on-error: true
      
      - name: Prepare deployment package
        run: |
          mkdir -p ../deploy/dist/driver-ranking
          cp -r dist package.json package-lock.json prisma node_modules ../deploy
          cp -r src/driver-ranking/ranking.py ../deploy/dist/driver-ranking/
          cp .env.example ../deploy/.env.example
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_39584EF908B24D9392814851987B59B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1C6C2ABD0D8442368C5299B18D4089ED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4D18475CDFBD4C1DB12908161780321D }}
      
      - name: Setup deployment environment
        run: |
          echo "PORT=8080" > .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'drivemate'
          slot-name: 'Production'
          package: .
      
      - name: Run database migrations
        run: |
          npm install
          npx prisma migrate deploy
